export type AdditiveRisk = 'low' | 'moderate' | 'high' | 'unrated';

export interface AdditiveInfo {
  code: string; // e.g. "E211"
  name: string;
  risk: AdditiveRisk;
  note: string;
}

// A curated reference table of additives commonly found on grocery packaging.
// Risk levels are a simplified public-reference classification (not medical
// advice) based on how these are broadly discussed by food-safety bodies
// (EFSA/ANSES) and consumer apps like Yuka — some are debated, and the aim
// here is a quick, consistent signal rather than a clinical judgment.
const ADDITIVE_DB: Record<string, Omit<AdditiveInfo, 'code'>> = {
  e100: { name: 'Curcumin', risk: 'low', note: 'Natural turmeric-derived color' },
  e101: { name: 'Riboflavin', risk: 'low', note: 'Vitamin B2, used as a color' },
  e120: { name: 'Cochineal / Carmine', risk: 'low', note: 'Natural insect-derived red color' },
  e122: { name: 'Azorubine / Carmoisine', risk: 'high', note: 'Synthetic dye linked to hyperactivity in children' },
  e102: { name: 'Tartrazine', risk: 'high', note: 'Synthetic yellow dye, hyperactivity warning in EU' },
  e104: { name: 'Quinoline Yellow', risk: 'high', note: 'Synthetic dye, hyperactivity warning in EU' },
  e110: { name: 'Sunset Yellow', risk: 'high', note: 'Synthetic dye, hyperactivity warning in EU' },
  e124: { name: 'Ponceau 4R', risk: 'high', note: 'Synthetic red dye, hyperactivity warning in EU' },
  e129: { name: 'Allura Red', risk: 'high', note: 'Synthetic red dye, hyperactivity warning in EU' },
  e150a: { name: 'Plain Caramel', risk: 'low', note: 'Caramel color' },
  e150c: { name: 'Ammonia Caramel', risk: 'moderate', note: 'Caramel color, may contain trace 4-MEI' },
  e150d: { name: 'Sulphite Ammonia Caramel', risk: 'moderate', note: 'Caramel color, may contain trace 4-MEI' },
  e160a: { name: 'Beta-Carotene', risk: 'low', note: 'Natural orange color, vitamin A precursor' },
  e162: { name: 'Beetroot Red', risk: 'low', note: 'Natural color from beets' },
  e163: { name: 'Anthocyanins', risk: 'low', note: 'Natural plant-derived color' },
  e171: { name: 'Titanium Dioxide', risk: 'high', note: 'Banned as a food additive in the EU since 2022' },
  e200: { name: 'Sorbic Acid', risk: 'low', note: 'Common natural-origin preservative' },
  e202: { name: 'Potassium Sorbate', risk: 'low', note: 'Widely used, well-tolerated preservative' },
  e211: { name: 'Sodium Benzoate', risk: 'moderate', note: 'Can form benzene when combined with vitamin C' },
  e212: { name: 'Potassium Benzoate', risk: 'moderate', note: 'Same family as sodium benzoate' },
  e220: { name: 'Sulphur Dioxide', risk: 'moderate', note: 'Common allergen, especially for asthma sufferers' },
  e223: { name: 'Sodium Metabisulphite', risk: 'moderate', note: 'Sulphite preservative, allergen risk' },
  e249: { name: 'Potassium Nitrite', risk: 'high', note: 'Cured-meat preservative linked to processed meat cancer risk' },
  e250: { name: 'Sodium Nitrite', risk: 'high', note: 'Cured-meat preservative linked to processed meat cancer risk' },
  e251: { name: 'Sodium Nitrate', risk: 'high', note: 'Cured-meat preservative linked to processed meat cancer risk' },
  e252: { name: 'Potassium Nitrate', risk: 'high', note: 'Cured-meat preservative linked to processed meat cancer risk' },
  e260: { name: 'Acetic Acid', risk: 'low', note: 'Vinegar acid' },
  e270: { name: 'Lactic Acid', risk: 'low', note: 'Naturally occurring acid' },
  e296: { name: 'Malic Acid', risk: 'low', note: 'Naturally occurring fruit acid' },
  e300: { name: 'Ascorbic Acid (Vitamin C)', risk: 'low', note: 'Vitamin C, also an antioxidant' },
  e301: { name: 'Sodium Ascorbate', risk: 'low', note: 'Vitamin C salt, antioxidant' },
  e306: { name: 'Tocopherol (Vitamin E)', risk: 'low', note: 'Natural antioxidant' },
  e307: { name: 'Synthetic Tocopherol', risk: 'low', note: 'Synthetic vitamin E antioxidant' },
  e320: { name: 'BHA', risk: 'high', note: 'Possible carcinogen, restricted in several countries' },
  e321: { name: 'BHT', risk: 'moderate', note: 'Synthetic antioxidant, debated safety' },
  e322: { name: 'Lecithin', risk: 'low', note: 'Common emulsifier, often from soy or sunflower' },
  e330: { name: 'Citric Acid', risk: 'low', note: 'Common natural-origin acid' },
  e339: { name: 'Sodium Phosphate', risk: 'moderate', note: 'Excess dietary phosphate linked to kidney/heart concerns' },
  e340: { name: 'Potassium Phosphate', risk: 'moderate', note: 'Excess dietary phosphate linked to kidney/heart concerns' },
  e401: { name: 'Sodium Alginate', risk: 'low', note: 'Seaweed-derived thickener' },
  e407: { name: 'Carrageenan', risk: 'moderate', note: 'Debated link to digestive irritation' },
  e410: { name: 'Locust Bean Gum', risk: 'low', note: 'Natural thickener' },
  e412: { name: 'Guar Gum', risk: 'low', note: 'Natural thickener' },
  e415: { name: 'Xanthan Gum', risk: 'low', note: 'Common fermentation-derived thickener' },
  e420: { name: 'Sorbitol', risk: 'low', note: 'Sugar alcohol, can cause bloating in large amounts' },
  e433: { name: 'Polysorbate 80', risk: 'moderate', note: 'Emulsifier, debated effect on gut lining' },
  e440: { name: 'Pectin', risk: 'low', note: 'Natural fruit-derived thickener' },
  e450: { name: 'Diphosphates', risk: 'moderate', note: 'Phosphate additive, excess intake concerns' },
  e451: { name: 'Triphosphates', risk: 'moderate', note: 'Phosphate additive, excess intake concerns' },
  e466: { name: 'Carboxymethyl Cellulose', risk: 'moderate', note: 'Emulsifier, debated effect on gut lining' },
  e471: { name: 'Mono- and Diglycerides', risk: 'low', note: 'Common emulsifier, source varies by product' },
  e477: { name: 'Propylene Glycol Esters', risk: 'moderate', note: 'Synthetic emulsifier' },
  e500: { name: 'Sodium Bicarbonate', risk: 'low', note: 'Baking soda' },
  e621: { name: 'Monosodium Glutamate (MSG)', risk: 'low', note: 'Flavor enhancer, safe for most; some report sensitivity' },
  e627: { name: 'Disodium Guanylate', risk: 'low', note: 'Flavor enhancer, often paired with MSG' },
  e631: { name: 'Disodium Inosinate', risk: 'low', note: 'Flavor enhancer, often paired with MSG' },
  e950: { name: 'Acesulfame K', risk: 'moderate', note: 'Artificial sweetener, debated long-term safety data' },
  e951: { name: 'Aspartame', risk: 'moderate', note: 'Artificial sweetener; WHO classed as "possibly carcinogenic" in 2023' },
  e952: { name: 'Cyclamate', risk: 'moderate', note: 'Artificial sweetener, banned in the US' },
  e954: { name: 'Saccharin', risk: 'moderate', note: 'Artificial sweetener, debated long-term safety data' },
  e955: { name: 'Sucralose', risk: 'low', note: 'Artificial sweetener, generally well-tolerated' },
  e957: { name: 'Thaumatin', risk: 'low', note: 'Natural protein-derived sweetener' },
  e959: { name: 'Neohesperidin DC', risk: 'low', note: 'Citrus-derived sweetener' },
  e960: { name: 'Steviol Glycosides (Stevia)', risk: 'low', note: 'Natural plant-derived sweetener' },
  e961: { name: 'Neotame', risk: 'moderate', note: 'Artificial sweetener, related to aspartame family' },
  e962: { name: 'Aspartame-Acesulfame Salt', risk: 'moderate', note: 'Combined artificial sweetener' },
  e965: { name: 'Maltitol', risk: 'low', note: 'Sugar alcohol, can cause bloating in large amounts' },
  e967: { name: 'Xylitol', risk: 'low', note: 'Sugar alcohol, well-tolerated in normal amounts' },

  // Additional colors
  e131: { name: 'Patent Blue V', risk: 'moderate', note: 'Synthetic dye, allergy risk in sensitive individuals' },
  e132: { name: 'Indigotine', risk: 'moderate', note: 'Synthetic blue dye, allergy risk in sensitive individuals' },
  e133: { name: 'Brilliant Blue FCF', risk: 'moderate', note: 'Synthetic dye, banned in some countries' },
  e140: { name: 'Chlorophylls', risk: 'low', note: 'Natural green color from plants' },
  e141: { name: 'Copper Chlorophyllin', risk: 'low', note: 'Natural-derived green color' },
  e142: { name: 'Green S', risk: 'moderate', note: 'Synthetic dye, banned in the US' },
  e153: { name: 'Vegetable Carbon', risk: 'low', note: 'Natural black color from charcoal' },
  e160b: { name: 'Annatto', risk: 'low', note: 'Natural color from achiote seeds' },
  e161b: { name: 'Lutein', risk: 'low', note: 'Natural carotenoid color, also an antioxidant' },
  e170: { name: 'Calcium Carbonate', risk: 'low', note: 'Chalk-derived color and firming agent' },
  e172: { name: 'Iron Oxides', risk: 'low', note: 'Mineral-based color' },
  e174: { name: 'Silver', risk: 'moderate', note: 'Metallic decorative color, minimal safety data' },
  e175: { name: 'Gold', risk: 'low', note: 'Metallic decorative color' },
  e180: { name: 'Litholrubine BK', risk: 'moderate', note: 'Synthetic dye used in cheese rinds' },

  // Additional preservatives
  e203: { name: 'Calcium Sorbate', risk: 'low', note: 'Common natural-origin preservative' },
  e210: { name: 'Benzoic Acid', risk: 'moderate', note: 'Can form benzene when combined with vitamin C' },
  e213: { name: 'Calcium Benzoate', risk: 'moderate', note: 'Same family as sodium benzoate' },
  e214: { name: 'Ethylparaben', risk: 'high', note: 'Paraben preservative, hormone-disruption concerns' },
  e218: { name: 'Methylparaben', risk: 'high', note: 'Paraben preservative, hormone-disruption concerns' },
  e219: { name: 'Sodium Methylparaben', risk: 'high', note: 'Paraben preservative, hormone-disruption concerns' },
  e221: { name: 'Sodium Sulphite', risk: 'moderate', note: 'Sulphite preservative, allergen risk' },
  e222: { name: 'Sodium Bisulphite', risk: 'moderate', note: 'Sulphite preservative, allergen risk' },
  e224: { name: 'Potassium Metabisulphite', risk: 'moderate', note: 'Sulphite preservative, allergen risk' },
  e226: { name: 'Calcium Sulphite', risk: 'moderate', note: 'Sulphite preservative, allergen risk' },
  e228: { name: 'Potassium Bisulphite', risk: 'moderate', note: 'Sulphite preservative, allergen risk' },
  e230: { name: 'Biphenyl', risk: 'high', note: 'Fungicide used on citrus peel, banned in the EU' },
  e231: { name: 'Orthophenyl Phenol', risk: 'high', note: 'Fungicide used on fruit peel, possible carcinogen' },
  e233: { name: 'Thiabendazole', risk: 'moderate', note: 'Fungicide used on fruit and vegetable peel' },
  e234: { name: 'Nisin', risk: 'low', note: 'Natural bacterial preservative' },
  e239: { name: 'Hexamine', risk: 'high', note: 'Preservative that can release formaldehyde' },
  e242: { name: 'Dimethyl Dicarbonate', risk: 'moderate', note: 'Beverage preservative, breaks down quickly' },
  e280: { name: 'Propionic Acid', risk: 'low', note: 'Natural mold-inhibiting acid' },
  e281: { name: 'Sodium Propionate', risk: 'low', note: 'Common bread preservative' },
  e282: { name: 'Calcium Propionate', risk: 'low', note: 'Common bread preservative' },

  // Acids, acidity regulators, and antioxidants
  e262: { name: 'Sodium Acetates', risk: 'low', note: 'Acidity regulator from acetic acid' },
  e263: { name: 'Calcium Acetate', risk: 'low', note: 'Acidity regulator from acetic acid' },
  e290: { name: 'Carbon Dioxide', risk: 'low', note: 'Carbonation gas' },
  e297: { name: 'Fumaric Acid', risk: 'low', note: 'Naturally occurring acid' },
  e304: { name: 'Ascorbyl Palmitate', risk: 'low', note: 'Fat-soluble form of vitamin C, antioxidant' },
  e310: { name: 'Propyl Gallate', risk: 'moderate', note: 'Synthetic antioxidant, debated safety' },
  e315: { name: 'Erythorbic Acid', risk: 'low', note: 'Antioxidant related to vitamin C' },
  e316: { name: 'Sodium Erythorbate', risk: 'low', note: 'Antioxidant related to vitamin C' },
  e325: { name: 'Sodium Lactate', risk: 'low', note: 'Naturally occurring salt of lactic acid' },
  e326: { name: 'Potassium Lactate', risk: 'low', note: 'Naturally occurring salt of lactic acid' },
  e327: { name: 'Calcium Lactate', risk: 'low', note: 'Naturally occurring salt of lactic acid' },
  e331: { name: 'Sodium Citrates', risk: 'low', note: 'Common acidity regulator from citric acid' },
  e332: { name: 'Potassium Citrates', risk: 'low', note: 'Common acidity regulator from citric acid' },
  e333: { name: 'Calcium Citrates', risk: 'low', note: 'Common acidity regulator from citric acid' },
  e334: { name: 'Tartaric Acid', risk: 'low', note: 'Naturally occurring grape acid' },
  e335: { name: 'Sodium Tartrates', risk: 'low', note: 'Salt of naturally occurring tartaric acid' },
  e336: { name: 'Potassium Tartrates (Cream of Tartar)', risk: 'low', note: 'Common baking acid' },
  e338: { name: 'Phosphoric Acid', risk: 'moderate', note: 'Excess dietary phosphate linked to kidney/heart concerns' },
  e350: { name: 'Sodium Malates', risk: 'low', note: 'Salt of naturally occurring malic acid' },
  e355: { name: 'Adipic Acid', risk: 'low', note: 'Synthetic acidity regulator, low toxicity' },
  e363: { name: 'Succinic Acid', risk: 'low', note: 'Naturally occurring acid' },
  e385: { name: 'Calcium Disodium EDTA', risk: 'moderate', note: 'Preservative that binds trace metals' },

  // Additional emulsifiers, thickeners, and stabilizers
  e400: { name: 'Alginic Acid', risk: 'low', note: 'Seaweed-derived thickener' },
  e404: { name: 'Calcium Alginate', risk: 'low', note: 'Seaweed-derived thickener' },
  e406: { name: 'Agar', risk: 'low', note: 'Natural seaweed-derived gelling agent' },
  e413: { name: 'Tragacanth Gum', risk: 'low', note: 'Natural plant-derived thickener' },
  e414: { name: 'Gum Arabic', risk: 'low', note: 'Natural tree-sap thickener' },
  e416: { name: 'Karaya Gum', risk: 'low', note: 'Natural plant-derived thickener' },
  e417: { name: 'Tara Gum', risk: 'low', note: 'Natural plant-derived thickener' },
  e422: { name: 'Glycerol', risk: 'low', note: 'Common humectant, generally well-tolerated' },
  e425: { name: 'Konjac', risk: 'low', note: 'Natural plant-derived thickener' },
  e426: { name: 'Soybean Hemicellulose', risk: 'low', note: 'Plant-fiber-derived stabilizer' },
  e435: { name: 'Polysorbate 65', risk: 'moderate', note: 'Emulsifier, debated effect on gut lining' },
  e436: { name: 'Polysorbate 60', risk: 'moderate', note: 'Emulsifier, debated effect on gut lining' },
  e441: { name: 'Gelatine', risk: 'low', note: 'Animal-derived gelling agent' },
  e442: { name: 'Ammonium Phosphatides', risk: 'moderate', note: 'Cocoa/chocolate emulsifier, phosphate additive' },
  e444: { name: 'Sucrose Acetate Isobutyrate', risk: 'moderate', note: 'Synthetic beverage stabilizer' },
  e445: { name: 'Glycerol Esters of Wood Rosin', risk: 'moderate', note: 'Synthetic beverage stabilizer' },
  e460: { name: 'Cellulose', risk: 'low', note: 'Plant-fiber-derived filler/thickener' },
  e461: { name: 'Methyl Cellulose', risk: 'low', note: 'Plant-fiber-derived thickener' },
  e463: { name: 'Hydroxypropyl Cellulose', risk: 'low', note: 'Plant-fiber-derived thickener' },
  e464: { name: 'Hydroxypropyl Methyl Cellulose', risk: 'low', note: 'Plant-fiber-derived thickener' },
  e469: { name: 'Enzymatically Hydrolysed Carboxymethyl Cellulose', risk: 'low', note: 'Modified plant-fiber thickener' },
  e470a: { name: 'Fatty Acid Salts', risk: 'low', note: 'Emulsifier from fatty acids' },
  e472a: { name: 'Acetic Acid Esters of Mono/Diglycerides', risk: 'low', note: 'Common emulsifier' },
  e472e: { name: 'DATEM', risk: 'moderate', note: 'Dough conditioner, some digestive concerns reported' },
  e473: { name: 'Sucrose Esters of Fatty Acids', risk: 'low', note: 'Sugar-derived emulsifier' },
  e474: { name: 'Sucroglycerides', risk: 'low', note: 'Sugar-derived emulsifier' },
  e475: { name: 'Polyglycerol Esters of Fatty Acids', risk: 'low', note: 'Common emulsifier' },
  e476: { name: 'Polyglycerol Polyricinoleate (PGPR)', risk: 'low', note: 'Chocolate/coating emulsifier' },
  e481: { name: 'Sodium Stearoyl Lactylate', risk: 'low', note: 'Common dough/baking emulsifier' },
  e491: { name: 'Sorbitan Monostearate', risk: 'low', note: 'Common emulsifier' },
  e492: { name: 'Sorbitan Tristearate', risk: 'low', note: 'Common emulsifier' },

  // Anti-caking, glazing, and gas agents
  e501: { name: 'Potassium Carbonates', risk: 'low', note: 'Common acidity regulator' },
  e503: { name: 'Ammonium Carbonates', risk: 'low', note: 'Traditional leavening agent' },
  e504: { name: 'Magnesium Carbonates', risk: 'low', note: 'Anti-caking agent' },
  e507: { name: 'Hydrochloric Acid', risk: 'low', note: 'Processing acid, fully neutralized in final product' },
  e508: { name: 'Potassium Chloride', risk: 'low', note: 'Common salt substitute mineral' },
  e509: { name: 'Calcium Chloride', risk: 'low', note: 'Common firming agent' },
  e511: { name: 'Magnesium Chloride', risk: 'low', note: 'Common firming agent, used in tofu-making' },
  e516: { name: 'Calcium Sulphate', risk: 'low', note: 'Common firming/anti-caking agent' },
  e524: { name: 'Sodium Hydroxide', risk: 'low', note: 'Processing aid, fully neutralized in final product' },
  e551: { name: 'Silicon Dioxide', risk: 'low', note: 'Common anti-caking agent' },
  e552: { name: 'Calcium Silicate', risk: 'low', note: 'Anti-caking agent' },
  e553b: { name: 'Talc', risk: 'moderate', note: 'Anti-caking mineral, purity/contamination concerns' },
  e558: { name: 'Bentonite', risk: 'low', note: 'Natural clay anti-caking/clarifying agent' },
  e559: { name: 'Aluminium Silicate', risk: 'moderate', note: 'Anti-caking agent, aluminium exposure concerns' },
  e570: { name: 'Fatty Acids', risk: 'low', note: 'Anti-foaming/glazing agent' },
  e900: { name: 'Dimethyl Polysiloxane', risk: 'low', note: 'Anti-foaming agent' },
  e901: { name: 'Beeswax', risk: 'low', note: 'Natural glazing agent' },
  e903: { name: 'Carnauba Wax', risk: 'low', note: 'Natural plant-derived glazing agent' },
  e904: { name: 'Shellac', risk: 'low', note: 'Natural insect-derived glazing agent' },
  e905: { name: 'Microcrystalline Wax', risk: 'moderate', note: 'Petroleum-derived glazing agent' },
  e938: { name: 'Argon', risk: 'low', note: 'Inert packaging gas' },
  e941: { name: 'Nitrogen', risk: 'low', note: 'Inert packaging gas' },
  e942: { name: 'Nitrous Oxide', risk: 'low', note: 'Propellant gas, e.g. for whipped cream' },
  e948: { name: 'Oxygen', risk: 'low', note: 'Packaging gas' },
  e949: { name: 'Hydrogen', risk: 'low', note: 'Packaging gas' },

  // Additional flavor enhancers
  e620: { name: 'Glutamic Acid', risk: 'low', note: 'Naturally occurring amino acid, flavor enhancer' },
  e622: { name: 'Potassium Glutamate', risk: 'low', note: 'Flavor enhancer, same family as MSG' },
  e623: { name: 'Calcium Glutamate', risk: 'low', note: 'Flavor enhancer, same family as MSG' },
  e626: { name: 'Guanylic Acid', risk: 'low', note: 'Flavor enhancer, often paired with MSG' },
  e630: { name: 'Inosinic Acid', risk: 'low', note: 'Flavor enhancer, often paired with MSG' },
  e635: { name: 'Disodium 5-Ribonucleotides', risk: 'low', note: 'Flavor enhancer, often paired with MSG' },

  // Modified starches (grouped under E1400s, common thickeners in processed food)
  e1400: { name: 'Dextrin', risk: 'low', note: 'Modified starch, common thickener' },
  e1401: { name: 'Acid-Treated Starch', risk: 'low', note: 'Modified starch, common thickener' },
  e1410: { name: 'Monostarch Phosphate', risk: 'low', note: 'Modified starch, common thickener' },
  e1412: { name: 'Distarch Phosphate', risk: 'low', note: 'Modified starch, common thickener' },
  e1413: { name: 'Phosphated Distarch Phosphate', risk: 'low', note: 'Modified starch, common thickener' },
  e1414: { name: 'Acetylated Distarch Phosphate', risk: 'low', note: 'Modified starch, common thickener' },
  e1420: { name: 'Acetylated Starch', risk: 'low', note: 'Modified starch, common thickener' },
  e1422: { name: 'Acetylated Distarch Adipate', risk: 'low', note: 'Modified starch, common thickener' },
  e1442: { name: 'Hydroxypropyl Distarch Phosphate', risk: 'low', note: 'Modified starch, common thickener' },
  e1450: { name: 'Starch Sodium Octenyl Succinate', risk: 'low', note: 'Modified starch, common emulsifying agent' },
};

/** Looks up an Open Food Facts additive tag (e.g. "en:e211") against our
 * reference table. Falls back to a generic "not rated" entry so unknown or
 * newly-tagged additives still render sensibly. */
export function lookupAdditive(tag: string): AdditiveInfo {
  const raw = tag.replace(/^en:/, '');
  const match = raw.match(/^e(\d+[a-z]?)/i);
  const code = match ? `E${match[1].toUpperCase()}` : raw.toUpperCase();
  const info = ADDITIVE_DB[code.toLowerCase()];
  if (info) return { code, ...info };
  return { code, name: code, risk: 'unrated', note: "Not in our reference table — we don't have public data to rate it" };
}
